name: medicine_inventory_frontend
services:
  frontend:
    image: ${IMAGE_URI:-ghcr.io/posdapal/medicine_inventory_system_frontend:latest}
    container_name: medicine_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:80"
